// <auto-generated />
using System;
using IT3047C_FinalProjectGroup6.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3047C_FinalProjectGroup6.Migrations
{
    [DbContext(typeof(RecipeContext))]
    [Migration("20221117210526_fifth")]
    partial class fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IT3047C_FinalProjectGroup6.Models.Recipe", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeEstimate")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Author = "Tony Gentile",
                            Description = "A bright and creamy tomato based pasta sauce served with Penne.",
                            Image = "https://www.cook2eatwell.com/wp-content/uploads/2018/05/Pasta-with-Vodka-Sauce-Image-1.jpg",
                            Ingredients = "Tomato Sauce, Heavy Whipping Cream, Olive Oil, Garlic, Pancetta (optional), Vodka, Basil, Penne",
                            Name = "Vodka Pasta",
                            TimeEstimate = 30
                        },
                        new
                        {
                            id = 2,
                            Author = "Karan Patel",
                            Description = "An unbeatable combination of both jelly and peanut butter between two slices of bread.",
                            Image = "https://www.gannett-cdn.com/media/2021/05/02/USATODAY/usatsports/imageForEntry14-XDZ.jpg",
                            Ingredients = "Peanut Butter, Jelly, Bread",
                            Name = "Peanut Butter and Jelly Sandwich",
                            TimeEstimate = 5
                        },
                        new
                        {
                            id = 3,
                            Author = "Saif Bayarri",
                            Description = "Cincinnati Chili is a famous dish in southwestern Ohio , with it’s most popular brand being Skyline Chili. The restaurant gets its name from the city skyline of Cincinnati.",
                            Image = "https://houseofnasheats.com/wp-content/uploads/2022/02/Cincinnati-Chili-Recipe-9-1.jpg",
                            Ingredients = "Ground Beef, Cheddar Cheese, Chocolate, Pasta",
                            Name = "Cincinnati Chili",
                            TimeEstimate = 45
                        },
                        new
                        {
                            id = 4,
                            Author = "JP Kelcewski",
                            Description = "A quick on-the-go meal with all the nutrients you need to start your day.",
                            Image = "https://lexiscleankitchen.com/wp-content/uploads/2017/10/Breakfast-Burritos-Freezer-Friendly5.jpg",
                            Ingredients = "Eggs, Bacon or Sausage, Shredded Cheese, Bell Peppers, Diced Potatoes, Tortillas.",
                            Name = "Breakfast Burrito",
                            TimeEstimate = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
